services:
  psql:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_volume:/data

  service:
    build:
        dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${REST_PORT}:8080"
    depends_on:
      - psql
      - redis
    environment:
      REST_PORT: ${REST_PORT}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_HOST: psql
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}

volumes:
  psql_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./db
  redis_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./redis